export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_TEAMS = 'GET_TEAMS';
export const FILTER_TEAMS = 'FILTER_TEAMS';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
export const FILTER_BY_ORDER = 'FILTER_BY_ORDER';
export const FILTER_BY_DATE = 'FILTER_BY_DATE';
export const RESET_FILTERS = 'RESET_FILTERS';
export const DELETE_DRIVER = 'DELETE_DRIVER';